# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imports/GUI_Argand_Sum.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1075, 679)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.doubleSpinBox_Pc_1stGr = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Pc_1stGr.setMaximum(1.0)
        self.doubleSpinBox_Pc_1stGr.setSingleStep(0.1)
        self.doubleSpinBox_Pc_1stGr.setProperty("value", 0.29)
        self.doubleSpinBox_Pc_1stGr.setObjectName(_fromUtf8("doubleSpinBox_Pc_1stGr"))
        self.gridLayout.addWidget(self.doubleSpinBox_Pc_1stGr, 2, 1, 1, 1)
        self.doubleSpinBox_Fc_ZL = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Fc_ZL.setMaximum(1.0)
        self.doubleSpinBox_Fc_ZL.setSingleStep(0.1)
        self.doubleSpinBox_Fc_ZL.setProperty("value", 0.53)
        self.doubleSpinBox_Fc_ZL.setObjectName(_fromUtf8("doubleSpinBox_Fc_ZL"))
        self.gridLayout.addWidget(self.doubleSpinBox_Fc_ZL, 1, 2, 1, 1)
        self.doubleSpinBox_n_Sum = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_n_Sum.setEnabled(False)
        self.doubleSpinBox_n_Sum.setReadOnly(True)
        self.doubleSpinBox_n_Sum.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_n_Sum.setMinimum(-1.0)
        self.doubleSpinBox_n_Sum.setMaximum(2.0)
        self.doubleSpinBox_n_Sum.setObjectName(_fromUtf8("doubleSpinBox_n_Sum"))
        self.gridLayout.addWidget(self.doubleSpinBox_n_Sum, 4, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.doubleSpinBox_Qty_2ndGr = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Qty_2ndGr.setSingleStep(0.1)
        self.doubleSpinBox_Qty_2ndGr.setObjectName(_fromUtf8("doubleSpinBox_Qty_2ndGr"))
        self.gridLayout.addWidget(self.doubleSpinBox_Qty_2ndGr, 3, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.doubleSpinBox_Fc_1stGr = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Fc_1stGr.setMaximum(1.0)
        self.doubleSpinBox_Fc_1stGr.setSingleStep(0.1)
        self.doubleSpinBox_Fc_1stGr.setProperty("value", 1.0)
        self.doubleSpinBox_Fc_1stGr.setObjectName(_fromUtf8("doubleSpinBox_Fc_1stGr"))
        self.gridLayout.addWidget(self.doubleSpinBox_Fc_1stGr, 2, 2, 1, 1)
        self.doubleSpinBox_Pc_Sum = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Pc_Sum.setMinimum(-2.0)
        self.doubleSpinBox_Pc_Sum.setMaximum(2.0)
        self.doubleSpinBox_Pc_Sum.setObjectName(_fromUtf8("doubleSpinBox_Pc_Sum"))
        self.gridLayout.addWidget(self.doubleSpinBox_Pc_Sum, 4, 1, 1, 1)
        self.doubleSpinBox_n_2ndGr = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_n_2ndGr.setEnabled(False)
        self.doubleSpinBox_n_2ndGr.setReadOnly(True)
        self.doubleSpinBox_n_2ndGr.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_n_2ndGr.setMinimum(-1.0)
        self.doubleSpinBox_n_2ndGr.setMaximum(2.0)
        self.doubleSpinBox_n_2ndGr.setObjectName(_fromUtf8("doubleSpinBox_n_2ndGr"))
        self.gridLayout.addWidget(self.doubleSpinBox_n_2ndGr, 3, 4, 1, 1)
        self.doubleSpinBox_Pc_2ndGr = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Pc_2ndGr.setMaximum(1.0)
        self.doubleSpinBox_Pc_2ndGr.setSingleStep(0.1)
        self.doubleSpinBox_Pc_2ndGr.setProperty("value", 0.63)
        self.doubleSpinBox_Pc_2ndGr.setObjectName(_fromUtf8("doubleSpinBox_Pc_2ndGr"))
        self.gridLayout.addWidget(self.doubleSpinBox_Pc_2ndGr, 3, 1, 1, 1)
        self.doubleSpinBox_Fc_Sum = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Fc_Sum.setMinimum(-2.0)
        self.doubleSpinBox_Fc_Sum.setMaximum(2.0)
        self.doubleSpinBox_Fc_Sum.setObjectName(_fromUtf8("doubleSpinBox_Fc_Sum"))
        self.gridLayout.addWidget(self.doubleSpinBox_Fc_Sum, 4, 2, 1, 1)
        self.doubleSpinBox_Fc_2ndGr = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Fc_2ndGr.setMaximum(1.0)
        self.doubleSpinBox_Fc_2ndGr.setSingleStep(0.1)
        self.doubleSpinBox_Fc_2ndGr.setProperty("value", 1.0)
        self.doubleSpinBox_Fc_2ndGr.setObjectName(_fromUtf8("doubleSpinBox_Fc_2ndGr"))
        self.gridLayout.addWidget(self.doubleSpinBox_Fc_2ndGr, 3, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.doubleSpinBox_Qty_1stGr = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Qty_1stGr.setSingleStep(0.1)
        self.doubleSpinBox_Qty_1stGr.setProperty("value", 0.1)
        self.doubleSpinBox_Qty_1stGr.setObjectName(_fromUtf8("doubleSpinBox_Qty_1stGr"))
        self.gridLayout.addWidget(self.doubleSpinBox_Qty_1stGr, 2, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.doubleSpinBox_n_ZL = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_n_ZL.setEnabled(False)
        self.doubleSpinBox_n_ZL.setReadOnly(True)
        self.doubleSpinBox_n_ZL.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_n_ZL.setMinimum(-1.0)
        self.doubleSpinBox_n_ZL.setMaximum(2.0)
        self.doubleSpinBox_n_ZL.setObjectName(_fromUtf8("doubleSpinBox_n_ZL"))
        self.gridLayout.addWidget(self.doubleSpinBox_n_ZL, 1, 4, 1, 1)
        self.doubleSpinBox_n_1stGr = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_n_1stGr.setEnabled(False)
        self.doubleSpinBox_n_1stGr.setReadOnly(True)
        self.doubleSpinBox_n_1stGr.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_n_1stGr.setMinimum(-1.0)
        self.doubleSpinBox_n_1stGr.setMaximum(2.0)
        self.doubleSpinBox_n_1stGr.setObjectName(_fromUtf8("doubleSpinBox_n_1stGr"))
        self.gridLayout.addWidget(self.doubleSpinBox_n_1stGr, 2, 4, 1, 1)
        self.doubleSpinBox_Pc_ZL = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Pc_ZL.setMaximum(1.0)
        self.doubleSpinBox_Pc_ZL.setSingleStep(0.1)
        self.doubleSpinBox_Pc_ZL.setProperty("value", 0.97)
        self.doubleSpinBox_Pc_ZL.setObjectName(_fromUtf8("doubleSpinBox_Pc_ZL"))
        self.gridLayout.addWidget(self.doubleSpinBox_Pc_ZL, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.doubleSpinBox_Qty_Sum = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Qty_Sum.setEnabled(False)
        self.doubleSpinBox_Qty_Sum.setReadOnly(True)
        self.doubleSpinBox_Qty_Sum.setMinimum(-9.0)
        self.doubleSpinBox_Qty_Sum.setSingleStep(0.1)
        self.doubleSpinBox_Qty_Sum.setObjectName(_fromUtf8("doubleSpinBox_Qty_Sum"))
        self.gridLayout.addWidget(self.doubleSpinBox_Qty_Sum, 4, 3, 1, 1)
        self.doubleSpinBox_Qty_ZL = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Qty_ZL.setSingleStep(0.1)
        self.doubleSpinBox_Qty_ZL.setProperty("value", 1.0)
        self.doubleSpinBox_Qty_ZL.setObjectName(_fromUtf8("doubleSpinBox_Qty_ZL"))
        self.gridLayout.addWidget(self.doubleSpinBox_Qty_ZL, 1, 3, 1, 1)
        self.checkBox_keepTrackofSum = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_keepTrackofSum.setChecked(True)
        self.checkBox_keepTrackofSum.setObjectName(_fromUtf8("checkBox_keepTrackofSum"))
        self.gridLayout.addWidget(self.checkBox_keepTrackofSum, 6, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(1, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.doubleSpinBox_Fc_ZL, self.doubleSpinBox_Qty_ZL)
        MainWindow.setTabOrder(self.doubleSpinBox_Qty_ZL, self.doubleSpinBox_Fc_1stGr)
        MainWindow.setTabOrder(self.doubleSpinBox_Fc_1stGr, self.doubleSpinBox_Qty_1stGr)
        MainWindow.setTabOrder(self.doubleSpinBox_Qty_1stGr, self.doubleSpinBox_Fc_2ndGr)
        MainWindow.setTabOrder(self.doubleSpinBox_Fc_2ndGr, self.doubleSpinBox_Qty_2ndGr)
        MainWindow.setTabOrder(self.doubleSpinBox_Qty_2ndGr, self.doubleSpinBox_Fc_Sum)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_11.setText(_translate("MainWindow", "n", None))
        self.label_4.setText(_translate("MainWindow", "Sum", None))
        self.label_7.setText(_translate("MainWindow", "Zero-Layer", None))
        self.label.setText(_translate("MainWindow", "Component", None))
        self.label_6.setText(_translate("MainWindow", "1st graphene", None))
        self.label_2.setText(_translate("MainWindow", "Fc", None))
        self.label_5.setText(_translate("MainWindow", "2nd graphene", None))
        self.label_8.setText(_translate("MainWindow", "Quantity", None))
        self.label_3.setText(_translate("MainWindow", "Pc", None))
        self.checkBox_keepTrackofSum.setText(_translate("MainWindow", "keepTrackofSum", None))

